#syntax=docker/dockerfile:1

FROM node:18-bookworm AS base
RUN apt update && apt install -y libssl3

WORKDIR /app
COPY ./.yarn/ .yarn/
COPY .yarnrc.yml .yarnrc.yml
COPY desktop desktop/
COPY server server/
COPY jobrunner jobrunner/
COPY package.json package.json
COPY yarn.lock yarn.lock
RUN --mount=type=cache,id=bowser-yarn,target=.yarn/cache yarn install --immutable

# NB: Please keep everything above this line the same in all the Dockerfiles, to properly leverage the Docker cache
